name: Python codeqa/test

on:
  push:
    branches:
      - coverage-debugging

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, pypy3]
        exclude:
        - os: macos-latest
          python-version: 3.7
        - os: macos-latest
          python-version: pypy3
        - os: windows-latest
          python-version: 3.7
        - os: windows-latest
          python-version: pypy3  # https://github.com/python-trio/trio/issues/1361
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install .[test,curio,trio]
    - name: Test with pytest
      run: coverage run -p -m pytest
    - name: Upload Coverage artifacts
      uses: actions/upload-artifact@v2
      with:
        name: coverage-data
        path: .coverage.*

  coveralls:
    name: Upload coverage to Coveralls
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Download coverage artifacts
      uses: actions/download-artifact@v2
      id: download
      with:
        name: coverage-data
    - name: Install Coverage and Coveralls
      run: pip install coverage coveralls
    - name: Upload to Coveralls
      run: |
        ls -lR ${{steps.download.outputs.download-path}}
        coverage combine ${{steps.download.outputs.download-path}}
        coverage debug data
        coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
